import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "BMI Calculator";
    in property <string> results: "";
    callback calculate-bmi(string, string);

    background: #043d8e;

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter your weight and height";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            weight := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                placeholder-text: "Enter your weight in kg";
                height: 35px;
            }
        }
        Row {
            height := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                placeholder-text: "Enter your height in m, e.g. 1.75";
                height: 35px;
            }
        }
        Row {
            Button {
                text: "calculate";
                padding-top: 30px;
                height: 35px;
                primary: true;
                clicked => {
                     root.calculate-bmi(weight.text, height.text);
                }
            }
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
